wandb_version: 1

_wandb:
  desc: null
  value:
    bounding_box/class_labels:
      Bounding Box Debugger/Images_wandb_delimeter_predictions:
        key: Bounding Box Debugger/Images_wandb_delimeter_predictions
        type: bounding_box/class_labels
        value:
          '0': Tuta absoluta
    cli_version: 0.12.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.6
    start_time: 1635563703
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 2
      4: 3.9.6
      5: 0.12.4
      8:
      - 5
anchor_t:
  desc: null
  value: 4.45427
anchors:
  desc: null
  value: 2.8649
batch_size:
  desc: null
  value: 6
box:
  desc: null
  value: 0.04365
cls:
  desc: null
  value: 0.0
cls_pw:
  desc: null
  value: 0
copy_paste:
  desc: null
  value: 0
data:
  desc: null
  value: data/eden_handpicked_v4.2.yaml
data_dict:
  desc: null
  value:
    anchors:
    - - 20
      - 21
      - 37
      - 25
      - 27
      - 38
    - - 44
      - 41
      - 40
      - 62
      - 66
      - 51
    - - 59
      - 80
      - 94
      - 89
      - 120
      - 157
    names:
    - Tuta absoluta
    nc: 1
    path: /home/innovation/Projects/greensprayer-disease-detection/eden-yolo-handpicked_v4.2/
    test: /home/innovation/Projects/greensprayer-disease-detection/eden-yolo-handpicked_v4.2/test_large/images
    train: /home/innovation/Projects/greensprayer-disease-detection/eden-yolo-handpicked_v4.2/train/images
    val: /home/innovation/Projects/greensprayer-disease-detection/eden-yolo-handpicked_v4.2/val/images
degrees:
  desc: null
  value: 0
epochs:
  desc: null
  value: 35
fl_gamma:
  desc: null
  value: 0
fliplr:
  desc: null
  value: 0.5
flipud:
  desc: null
  value: 0
hsv_h:
  desc: null
  value: 0
hsv_s:
  desc: null
  value: 0
hsv_v:
  desc: null
  value: 0
img:
  desc: null
  value: 1024
iou_t:
  desc: null
  value: 0.2
label_smoothing:
  desc: null
  value: 0.0
lr0:
  desc: null
  value: 0.007597718567629481
lrf:
  desc: null
  value: 0.09591882520101341
mixup:
  desc: null
  value: 0
momentum:
  desc: null
  value: 0.9662731557237416
mosaic:
  desc: null
  value: 0
obj:
  desc: null
  value: 1.6411392000000005
obj_pw:
  desc: null
  value: 0.76736
perspective:
  desc: null
  value: 0
scale:
  desc: null
  value: 0
shear:
  desc: null
  value: 0
translate:
  desc: null
  value: 0
warmup_bias_lr:
  desc: null
  value: 0.01733216573766666
warmup_epochs:
  desc: null
  value: 0.06461052824026314
warmup_momentum:
  desc: null
  value: 0.8158926252513238
weight_decay:
  desc: null
  value: 0.0008442086201436538
weights:
  desc: null
  value: yolov5l.pt
